---
- name: Set passenger ruby to system one
  become: true
  lineinfile:
    dest: "{{nginx_path}}/conf/nginx.conf"
    regexp: "^(\\s*)#\\s*passenger_ruby"
    line: "passenger_ruby /usr/local/bin/ruby;"
    backrefs: yes

- name: Set passenger root to system one
  become: true
  lineinfile:
    dest: "{{nginx_path}}/conf/nginx.conf"
    regexp: "^(\\s*)#\\s*passenger_root"
    line: "passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;"
    backrefs: yes
