---
- name: restart postgres
  become: true
  service:
    name: postgresql
    state: restarted
  listen: "restart data services"

- name: reload postgres
  become: true
  service:
    name: postgresql
    state: reloaded
  listen: "reload data services"
