---
- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install aptitude
  become: true
  apt:
    name: aptitude

- name: Update apt packages
  become: true
  apt:
    upgrade: yes
